#!/bin/sh
#
# Clear system event log via IPMI
#
# Usage: ipmi-clear-log

usage () {
    COUNT=`cat $0 | tail -n +3 | grep -n '^$' -m 1 | cut -d ':' -f 1`
    cat $0 | tail -n +3 | head -n $COUNT | colrm 1 2
    exit 1
}
echo " " $@ | grep ' --help' > /dev/null && usage

if [ -n "$1" ]; then
    usage
fi

echo Clearing system event log as root ...
echo
sudo ipmitool sel clear
